### ISSUE TITLE
multiple go carbon processes writing to same data directory

### ISSUE THREAD

**Issue by dopey** [similarweb/puppet-go_carbon#2]
Hi,

I am currently using graphite/carbon with multiple caches. I've been wanting to try out go-carbon and this module looks great as it seems to be doing most of the work for me :)

Is it necessary to have the instances write to separate data directories (e.g. /data/whisper1, /data/whisper2)? Its not a deal breaker that the data directory gets split, but Im wondering if this would cause issues in the future if, for example, I decided to have fewer or more instances running per machine.

cheers,
max

**Comment by danielbenzvi** [comment]
Hey Max
I do hope you'd find this module useful and feel free to submit a pull request if you want to enhance it :-)

It's not necessary to run more than one instance, so you don't have to split at all. We do so, because we have multiple SSD drives and we didn't want to use a RAID controller for maximum throughput. 

If you don't want to split - just declare one instance and you're good to go.

**Comment by dopey** [comment]
Got it. Thanks! Didn't realize that go-carbon was already multi-threaded.

cheers!
